---
version: '3'
services:
  infra-assessment:
    container_name: infra-test-arun
    image: infracloudio/csvserver
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
    network_mode: "testing"

  prometheus:
    container_name: monitor
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "testing"
