---
version: '3'
services:
  infra-assessment:
    container_name: infra-test-arun
    image: infracloudio/csvserver
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
